### ISSUE TITLE
Success and error message received from system bot instead of Google Drive bot

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost-community/mattermost-plugin-google-drive#7]
On uploading the files to drive from the action menu button, the success and error message are received from the system bot, instead of drive bot.

**Steps to reproduce:**

- Post any attachement in the channel.
- Open the action menu.
- Click on upload the file to drive.
- 
The success message or the error message will be received from the system bot which should have been received from the google drive bot.

**Comment by darkLord19** [comment]
@AayushChaudhary0001 this is fixed in master.

**Comment by AayushChaudhary0001** [comment]
This issue was re-tested and the google-drive bot sends the success message, but the error message is still presented the by the system bot, please verify.

**Comment by BenCookie95** [comment]
@AayushChaudhary0001 Can you show me a screenshot of the error you are getting from system bot please? I don't get any error feedback if an upload fails

**Comment by AayushChaudhary0001** [comment]
Please refer to this screenshot
![image](https://github.com/user-attachments/assets/0c54bc27-89d6-421e-a202-ce6d92a09b6d)

**Comment by BenCookie95** [comment]
This [PR](https://github.com/mattermost-community/mattermost-plugin-google-drive/pull/16) should fix that issue because you won't be able to get into that state anymore
